spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/project_1
    username: root
    password: green502
  jpa:
    open-in-view: false
    properties:
      hibernate:
        cache.use_second_level_cache: false  # JCache 설정 비활성화
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  data:
    redis:
      port: 6379
      host: 192.168.0.144

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true
  cache:
    disabled: true

file:
  directory: D:/home/download

---
spring:
   config:
     activate:
       on-profile: prod
   data:
     redis:
       port: 6379
       host: 192.168.0.144
   datasource:
     url: jdbc:log4jdbc:mariadb://192.168.0.144:3306/db_odd_first_2
     username: odd_first_2
     password: channel
   jpa:
     open-in-view: false
     properties:
       hibernate:
         cache.use_second_level_cache: false
   servlet:
     multipart:
       max-file-size: 1000MB
       max-request-size: 1000MB

mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true
  cache:
    disabled: true

file:
   directory: /home/download
